config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  resources :publications do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]    
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :publication
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin_or_author, only: [:update, :edit, :destroy]
  before_action :set_comment, only: [:show, :edit, :update, :destroy ]
  # before_action :set_publication, only: [:create, :show, :edit, :update, :destroy ] 
  
  
  # GET /comments or /comments.json
  def index
    @comments = Comment.all
  end

  # GET /comments/1 or /comments/1.json
  def show
    @publication =  Publication.find(params[:publication_id])
    @comment =  @publication.comments.find(params[:id])
  end

  # GET /comments/new
  def new
   @publication =  Publication.find(params[:publication_id])
   @comment =  @publication.comments.build
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments or /comments.json
  def create
    @publication = Publication.find(params[:publication_id])
    @comment = @publication.comments.build(comment_params)
    @comment.user = current_user       

    respond_to do |format|
      if @comment.save
        format.html { redirect_to @publication, notice: "Comentario creado exitosamente." }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1 or /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: "Comentario actualizado exitosamente." }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1 or /comments/1.json
  def destroy
    @publication = @comment.publication
    @comment.destroy

    respond_to do |format|
      format.html { redirect_to  publication_path( @publication), notice: "Comentario eliminado exitosamente" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.require(:comment).permit(:content, :user_id, :publication_id)
    end

    def authorize_admin_or_author
      unless current_user.admin? || (@publication && current_user.id == @publication.user_id)
        redirect_to home_index_path, notice: "No estás autorizado para hacer esta acción"
      end
    end
  end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>">
  <p>
    <%= image_tag current_user.image, class: 'rounded-circle-comment  mb-3'%>
    <strong>Content:</strong>
    <%= comment.content %>
  </p>
</div>

app/views/comments/_form.html.erb
<%= form_with(model:  [@publication, @comment]) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> No se pudo guardar el comentario</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container mt-5">
    <div>
      <%= image_tag current_user.image, class: 'rounded-circle-comment  mb-3'%>
      <%= form.text_area :content, class:"form-control" %>
      
    </div>    

    <div>
      <%=form.hidden_field :user_id, value: current_user.id  %>
    </div>

    <div>
      <%= form.hidden_field :publication_id, value: @publication.id  %>
    </div><br/>    

    <div>
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_publication_comment_path, method: :get, class: "btn btn btn-secondary text-white mt-3 mb-3" %>

app/views/comments/new.html.erb
<div class="container">
  <h1>Nuevo Comentario</h1>

  <%= render "form", comment: @comment %>

  <br>

 <div class="container mt-3 text-center">  
  <%= link_to "Volver a la publicación", publication_path(@publication) %>
  </div>
</div>

app/views/comments/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>