config/routes.rb
Rails.application.routes.draw do
  
  get 'home/index'
  resources :publications do
    resources :comments, only: [:new, :create, :show, :edit, :update, :destroy]    
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
   }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"
end

app/models/publication.rb
class Publication < ApplicationRecord
 belongs_to :user
 has_many :active_storage_attachments, as: :record, class_name: 'ActiveStorage::Attachment', dependent: :destroy
 has_many_attached :images
 has_many :comments
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_admin, only: [:create, :update, :edit, :destroy]
  before_action :set_publication, only: [ :show, :edit, :update, :destroy ]

  # GET /publications or /publications.json
  def index
    @publications = Publication.all
  end

  # GET /publications/1 or /publications/1.json
  def show
    @publication = Publication.find(params[:id])
    @comments = @publication.comments
  end

  # GET /publications/new
  def new
    @publication = Publication.new
  end

  # GET /publications/1/edit
  def edit
  end

  # POST /publications or /publications.json
  def create
    @publication = Publication.new(publication_params)
    @publication.user = current_user
    @publication.images.attach(params[:publication][:images])

    respond_to do |format|
      if @publication.save
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully created." }
        format.json { render :show, status: :created, location: @publication }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /publications/1 or /publications/1.json
  def update
    respond_to do |format|
      if @publication.update(publication_params)
        format.html { redirect_to publication_url(@publication), notice: "Publication was successfully updated." }
        format.json { render :show, status: :ok, location: @publication }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @publication.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /publications/1 or /publications/1.json
  def destroy
    @publication.destroy

    respond_to do |format|
      format.html { redirect_to publications_url, notice: "Publication was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_publication
      @publication = Publication.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def publication_params
      params.require(:publication).permit(:description, :user_id, :images)
    end

    def authorize_admin
      unless current_user.admin?
        redirect_to home_index_path, notice: "No estás autorizado para hacer esta acción"
      end
    end
end

app/helpers/publications_helper.rb
module PublicationsHelper
end

app/views/publications/_form.html.erb
<%= form_with(model: publication) do |form| %>
  <% if publication.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(publication.errors.count, "error") %> prohibited this publication from being saved:</h2>

      <ul>
        <% publication.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :descripción, style: "display: block" %>
    <%= form.text_area :description, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :foto %>
    <%= form.file_field :images, multiple: true, class: 'form-control' %>
  </div><br/>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/publications/_index.html.erb
<p style="color: green"><%= notice %></p>

<div class= "container-fluid">
  <div id="notes" class="row row-cols-1 row-cols-md-3 g-4">
    <% @publications.each do |publication| %> 
      <div class="col"> 
        <%= render publication %>          
      </div>    
    <% end %>
  </div> 
</div>

app/views/publications/_publication.html.erb
   
<div class="container d-flex justify-content-center align-items-center">
    <div id="<%= dom_id(publication) if publication.present? %>"> 
          <div class="card w-75">        
              <div class="card-body">
                  <% publication.images.each do |image| %>
                    <%= image_tag image, class: "card-img-top" if image.present? %>
                  <% end %>          
                <p class="card-text text-start"> <p><strong></strong><%= publication.description %></p></p> 
              </div>
              <div class= "ver_publicacion text-center">
                <%= link_to "Ver publicación", publication, class: "nav-link" %>    
              </div>
          </div>
     </div>
</div>

app/views/publications/edit.html.erb
<div class="container">
  <div class="row">
      <div class="col-3">
      </div>
      <div class="col">
        <h1>Editar Publicación</h1>

        <%= render "form", publication: @publication %><br>
        <%= link_to "Show this publication", @publication %> |
        <%= link_to "Back to publications", publications_path %>
      </div>
        
      <div class="col-3">
      
          
      </div>
  </div>
</div>

app/views/publications/index.html.erb
<p style="color: green"><%= notice %></p>

<div class= "container-fluid">
  <div id="notes" class="row row-cols-1 row-cols-md-3 g-4">
    <% @publications.each do |publication| %> 
      <div class="col"> 
        <%= render publication %>          
      </div>
    </div>
    <% end %>
  </div>

app/views/publications/new.html.erb
<div class="container">
  <div class="row">
      <div class="col">
      </div>
      <div class="col">
          <h1>Crear Publicación</h1>
          <%= render "form", publication: @publication %>
      </div>
      <div class="col">
      </div>          
      <div class="container mt-5 text-center">    
          <%= link_to "Volver a las publicaciones", home_index_path %>  
      </div>      
    </div>
</div>

app/views/publications/show.html.erb
    
<div class="container d-block justify-content-center align-items-center">
      <p style="color: green"><%= notice %></p>
      

  <div class="row">
    <div class="col-3">
    </div>
    <div class="col">
      <%= render partial: 'publication', locals: { publication: @publication } %>
          <nav class="nav pt-3 pb-3">
            <% if user_signed_in? %>
              <div class="d-flex">           
                <%= button_to "Comentar", new_publication_comment_path(@publication), method: :get, class: "btn btn btn-secondary text-white mt-2 ms-3" %>            
              </div>
            <% end %>
            <% if current_user.admin? || current_user.id == @publication.user_id %>          
              <div class="d-flex">
                <%= button_to "Editar", edit_publication_path(@publication), method: :get, class: "btn btn btn-secondary mt-2 ms-3" %>
                <%= button_to "Eliminar", publication_path(@publication), method: :delete, data: { confirm: "¿Estás seguro?" }, class: "btn btn btn-secondary  mt-2 ms-3 me-5" %>      
              </div>  
            <% end %>   
          </nav>
          <div class="card text-bg-tertiary mb-3 mt-5 ms-3" style="max-width: 18rem;">
            <div class="card-header">Comentarios</div>
              <div class="card-body">        
                <h5 class="card-title"></h5>
                <p class="card-text">
                  <% @comments.each do |comment| %>
                        <%= render comment %></p>
                        <%= link_to "Ver", publication_comment_path(@publication, comment), class: "nav-link" %>
                  <% end %>
              </div>
            </div>
          </div>
    </div>
    <div class="col-3">          
    </div>
       
          <nav class="nav pt-2 pb-3 ms-5 justify-content-center">
                 
          </nav>      
          
    
      
         
</div>